version: '3.9'

services:

  postgres:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=spring
    networks:
      - spring-cloud-network


  my-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge